source:      .
destination: ./_site
plugins:     ./_plugins
posts: 	     ./_posts
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
markdown: kramdown
name: mZero
description: Ideias para simplificar
url: http://mzero.devagar.org
safe: true
lsi: false
pygments: true